name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # 如果你的默认分支叫 master，请改成 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - run: pip install mkdocs-material
      
      - run: mkdocs build -f mkdocs.yml -d site
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
